### PR TITLE
render: Fix bug to rerender tables; switch to byte buffers.

### LINKED ISSUE #28: Table can't render cleanly twice if has headers
Given this code, we should see just one line of output, `ok`.  We don't.  Instead, we see the mismatch output below.

``` go
package main

import (
    "fmt"
    "os"

    "github.com/apcera/termtables"
)

func main() {
    tb := termtables.CreateTable()
    tb.AddHeaders("foo", "bar")
    tb.AddRow("a", "b")

    r1 := tb.Render()
    r2 := tb.Render()

    if r1 == r2 {
        fmt.Printf("ok\n")
    } else {
        fmt.Printf("MISMATCH!\nRender 1:\n%s\nRender 2:\n%s\n", r1, r2)
        os.Exit(1)
    }
}
```

Output:

```
% go run table_twice.go 
MISMATCH!
Render 1:
+-----+-----+
| foo | bar |
+-----+-----+
| a   | b   |
+-----+-----+

Render 2:
+-----+-----+
| foo | bar |
+-----+-----+
+-----+-----+
| foo | bar |
+-----+-----+
| a   | b   |
+-----+-----+

exit status 1
```

If we add a call `tb.UTF8Box()` immediately after creation, then the nature the headers becomes slightly clearer:

```
% go run table_twice.go
MISMATCH!
Render 1:
╭─────┬─────╮
│ foo │ bar │
├─────┼─────┤
│ a   │ b   │
╰─────┴─────╯

Render 2:
╭─────┬─────╮
│ foo │ bar │
├─────┼─────┤
╭─────┬─────╮
│ foo │ bar │
├─────┼─────┤
│ a   │ b   │
╰─────┴─────╯

exit status 1
```

### PR DESCRIPTION
**Pull request by johnSchnake**
The elements of the table were being modified on each call
to Render, leading to headers and titles being compounded.
This fixes the bug by utilizing a deep-ish copy of the table.

In addition, I noticed raw string concatenation in Render
which I swapped out for bytes.Buffer calls which led to a
95% reduction in the duration of the call.

Fixes #28 

Pulled benchmarks from #35 as they proved useful here too.

### CODE REVIEW

**Comment by johnSchnake** [comment]
After swapping this out I'm interested in seeing what speedup remains when caching the width calculation in #35 ; I can split out the changes into different PRs if desired, it was just a fixup while I was there and editing it.

File: table.go [hunk 1]
```diff
@@ -238,61 +240,68 @@ func (t *Table) Render() (buffer string) {
...
 		}
-		t.elements = append(ne, t.elements...)
+		tt.elements = append(ne, tt.elements...)
 	}
 
-	// if we have a title, write them
-	if t.title != nil {
-		// match changes to this into renderMarkdown too
-		t.titleCell = CreateCell(t.title, &CellStyle{Alignment: AlignCenter, ColSpan: 999})
+	// If we have a title, write them.
```
Comment (y0ssar1an) [inline table.go]: nit: `them` -> `it`

File: table.go [hunk 2]
```diff
@@ -238,61 +240,68 @@ func (t *Table) Render() (buffer string) {
...
 
-	// loop over the elements and render them
-	for _, e := range t.elements {
-		buffer += e.Render(style) + "\n"
+	// Loop over the elements and render them.
+	b := bytes.NewBuffer(nil)
+	for _, e := range tt.elements {
+		b.WriteString(e.Render(style))
+		b.WriteString("\n")
 	}
```
Comment (y0ssar1an) [inline table.go]: 👍

File: table_test.go [hunk 3]
```diff
@@ -450,3 +478,47 @@ func TestTableMultipleAddHeader(t *testing.T) {
 
 	checkRendersTo(t, table, expected)
 }
+
+func createTestTable() *Table {
+	table := CreateTable()
+	header := []interface{}{}
+	for i := 0; i < 50; i++ {
+		header = append(header, "First Column")
+	}
```
Comment (y0ssar1an) [inline table_test.go]: extremely-minor-nit: You can use `make([]interface{}, 50)` to save a few allocations here and with the `row` below. might save a whole millisecond :)

File: table_test.go [hunk 4]
```diff
@@ -450,3 +478,47 @@ func TestTableMultipleAddHeader(t *testing.T) {
...
+}
+
+func BenchmarkTableRenderHTML(b *testing.B) {
+	table := createTestTable()
+	table.SetModeHTML()
+	b.ResetTimer()
+	for i := 0; i < b.N; i++ {
+		table.Render()
+	}
+}
```
Comment (y0ssar1an) [inline table_test.go]: 👍

**Comment by johnSchnake** [comment]
Just fixed up a comment; merging after green.
